module.exports = {
  parser: 'postcss-scss',
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      stage: 1,
      features: {
        'nesting-rules': true,
      },
    },
    'postcss-selector-matches': {},
    'postcss-selector-not': {},
    'postcss-color-mod-function': {},
    'postcss-apply': {},
    'postcss-atroot': {},
    'postcss-property-lookup': {},
    'postcss-replace-overflow-wrap': {},
    'postcss-will-change': {},
    'postcss-viewport-units': {},
    'postcss-zindex': {},
    'postcss-merge-rules': {},
    'postcss-merge-longhand': {},
    'postcss-minify-selectors': {},
    'postcss-normalize-charset': {},
    'postcss-normalize-display-values': {},
    'postcss-normalize-string': {},
    'postcss-normalize-timing-functions': {},
    'postcss-normalize-unicode': {},
    'postcss-normalize-url': {},
    'postcss-normalize-whitespace': {},
    'postcss-ordered-values': {},
    'postcss-reduce-initial': {},
    'postcss-reduce-transforms': {},
    'postcss-svgo': {},
    'postcss-unique-selectors': {},
    'postcss-pxtorem': {},
    'postcss-automath': {},
    'postcss-calc': {},
    'postcss-color-function': {},
    'postcss-convert-values': {},
    'postcss-custom-media': {},
    'postcss-custom-properties': {},
    'postcss-custom-selectors': {},
    'postcss-extend-rule': {},
    'postcss-media-minmax': {},
    'postcss-nesting': {},
    'postcss-nested': {},
    'postcss-quantity-queries': {},
  }
}